sudo: false
matrix:
  include:
    - language: node_js
      cache: yarn
      node_js: node

    - language: node_js
      cache: yarn
      node_js: lts/*

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
script:
  - yarn test:coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
