# This workflow will do a clean install of node dependencies and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: npm

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js LTS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install project dependencies
        run: yarn install --frozen-lockfile

      - name: Run linting
        run: yarn lint
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install project dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test
